
#jpa配置数据库
#server:
#  port: 8080
#girl:
#  cupSize: A
#  age : 18
#  content: "cupSize: ${cupSize}, age: ${age} "
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/dbgirl
#    username: root
#    password: mypassword
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
